# Site settings
title: Albert Cid Royo - Pottery
email: albertcidroyo@gmail.com
author: albertcidRoyo

keywords: portfolio, artist, works, ceramics, artist, pottery, ACR Figulus, Albert Cid Royo
description:

# Only use this if you are serving your site via Github Pages
#github:
 # url: "aidonnou.github.io"

header: 'https://lh6.googleusercontent.com/S4iPK-jKMpkBGwBvWsuNdPO5YNf82mbKXKItYs1w3Cai-wHp9jko9X_5UnHbk56O7bI=w2400'

# Formspree contact Form
contact_form: "https://formspree.io/f/mzboqboo"


# Exclude our ruby stuff
exclude: [.bundle, .vendor, .bin, starving-artist.gemspec, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, starving-artist-jekyll-theme-*.gem]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

theme: minima
  
# Plugins
gems:
  - jekyll-feed

feed:
  path: atom.xml
  
# Compress our Css
#sass:
#    style: :compressed

include: ['_pages']

permalink: /blog/:year/:title

collections:
  - galleries
